# Generated by Django 5.0.6 on 2024-05-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tittle',
            new_name='title',
        ),
    ]
